### ISSUE TITLE
07_image_views: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by mewmew** [vkngwrapper/vulkan-tutorial#1]
I tried to build and run the various steps of the vulkan--tutorial, but ran into this issue on step `07_image_views`.

The test program `vkcube` is running without problem on my laptop, so at least Vulkan should be working.

Let me know what kind of info may help debug this issue. (e.g. `vulkaninfo` output, etc). I'm running Arch Linux, and have tried using both X11 and Wayland. Both seems to crash for step 07.

(Oh, and I just tested step `15_hello_triangle` and it renders correctly.. Screenshot at the bottom of this post)

```
$ ./07_image_views
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0x868530?, 0xffffffffffffffb8?})
	/home/u/go/src/runtime/panic.go:1075 +0x5c fp=0x7fff17d05740 sp=0x7fff17d05710 pc=0x4421dc
runtime.sigpanic()
	/home/u/go/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7fff17d057a0 sp=0x7fff17d05740 pc=0x457b29

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x743110, 0xc000119df0)
	/home/u/go/src/runtime/cgocall.go:157 +0x51 fp=0xc000119dc8 sp=0xc000119d90 pc=0x4115d1
github.com/vkngwrapper/core/v2/driver._Cfunc_driverFuncPtrs_populate(0x0, 0x2c37ce0)
	_cgo_gotypes.go:6554 +0x3f fp=0xc000119df0 sp=0xc000119dc8 pc=0x6bf9ff
github.com/vkngwrapper/core/v2/driver.CreateDriverFromProcAddr.func1(0x590?, 0x2c37ce0?)
	/home/u/goget/pkg/mod/github.com/vkngwrapper/core/v2@v2.1.2/driver/driver.go:63 +0x45 fp=0xc000119e30 sp=0xc000119df0 pc=0x6d1245
github.com/vkngwrapper/core/v2/driver.CreateDriverFromProcAddr(0x73d9f0?)
	/home/u/goget/pkg/mod/github.com/vkngwrapper/core/v2@v2.1.2/driver/driver.go:63 +0x46 fp=0xc000119e88 sp=0xc000119e30 pc=0x6d1146
github.com/vkngwrapper/core/v2.CreateLoaderFromProcAddr(0x0?)
	/home/u/goget/pkg/mod/github.com/vkngwrapper/core/v2@v2.1.2/iface.go:61 +0x13 fp=0xc000119eb0 sp=0xc000119e88 pc=0x7209f3
main.(*HelloTriangleApplication).initWindow(0xc000196000)
	/home/u/Desktop/vulkan-tutorial/steps/07_image_views/main.go:89 +0xa5 fp=0xc000119ef0 sp=0xc000119eb0 pc=0x734f65
main.(*HelloTriangleApplication).Run(0xc000196000)
	/home/u/Desktop/vulkan-tutorial/steps/07_image_views/main.go:62 +0x33 fp=0xc000119f38 sp=0xc000119ef0 pc=0x734d93
main.main()
	/home/u/Desktop/vulkan-tutorial/steps/07_image_views/main.go:563 +0x1f fp=0xc000119f80 sp=0xc000119f38 pc=0x736f7f
runtime.main()
	/home/u/go/src/runtime/proc.go:250 +0x207 fp=0xc000119fe0 sp=0xc000119f80 pc=0x444947
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000119fe8 sp=0xc000119fe0 pc=0x472de1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/u/go/src/runtime/proc.go:381 +0xd0 fp=0xc00004afb0 sp=0xc00004af90 pc=0x444d30
runtime.goparkunlock(...)
	/home/u/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/home/u/go/src/runtime/proc.go:305 +0xa5 fp=0xc00004afe0 sp=0xc00004afb0 pc=0x444ba5
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004afe8 sp=0xc00004afe0 pc=0x472de1
created by runtime.init.6
	/home/u/go/src/runtime/proc.go:293 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/u/go/src/runtime/proc.go:381 +0xd0 fp=0xc00004b780 sp=0xc00004b760 pc=0x444d30
runtime.goparkunlock(...)
	/home/u/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/home/u/go/src/runtime/mgcsweep.go:278 +0x88 fp=0xc00004b7c8 sp=0xc00004b780 pc=0x431b08
runtime.gcenable.func1()
	/home/u/go/src/runtime/mgc.go:178 +0x25 fp=0xc00004b7e0 sp=0xc00004b7c8 pc=0x427365
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004b7e8 sp=0xc00004b7e0 pc=0x472de1
created by runtime.gcenable
	/home/u/go/src/runtime/mgc.go:178 +0x6a

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000070000?, 0x8dd270?, 0x1?, 0x0?, 0x0?)
	/home/u/go/src/runtime/proc.go:381 +0xd0 fp=0xc00004bf70 sp=0xc00004bf50 pc=0x444d30
runtime.goparkunlock(...)
	/home/u/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xbad0e0)
	/home/u/go/src/runtime/mgcscavenge.go:399 +0x49 fp=0xc00004bfa0 sp=0xc00004bf70 pc=0x42fb09
runtime.bgscavenge(0x0?)
	/home/u/go/src/runtime/mgcscavenge.go:627 +0x3c fp=0xc00004bfc8 sp=0xc00004bfa0 pc=0x43009c
runtime.gcenable.func2()
	/home/u/go/src/runtime/mgc.go:179 +0x25 fp=0xc00004bfe0 sp=0xc00004bfc8 pc=0x427305
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004bfe8 sp=0xc00004bfe0 pc=0x472de1
created by runtime.gcenable
	/home/u/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x7f55ee27b108?, 0x1a0?, 0x70?, 0xa7?, 0x45161e?)
	/home/u/go/src/runtime/proc.go:381 +0xd0 fp=0xc00004a628 sp=0xc00004a608 pc=0x444d30
runtime.runfinq()
	/home/u/go/src/runtime/mfinal.go:193 +0xf8 fp=0xc00004a7e0 sp=0xc00004a628 pc=0x426418
runtime.goexit()
	/home/u/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004a7e8 sp=0xc00004a7e0 pc=0x472de1
created by runtime.createfing
	/home/u/go/src/runtime/mfinal.go:163 +0x3d
```

For reference, the `15_hello_triangle` example renders correctly.

![2023-04-24-120427_827x646_scrot](https://user-images.githubusercontent.com/1414531/233904403-09181b30-bc1d-4535-8722-5eeef6fe5f81.png)

**Comment by CannibalVox** [comment]
Does step 7 fail consistently or intermittently? I can't repro and this point of failure seems very arbitrary. It would almost make more sense to me if it was failing sometimes and succeeding at others. If you can get it to fail consistently, do me a favor and build the step to an executable, and run `gdb <go exe>` and `run` - that should I believe get us an actual stack trace for the failure point in C code

**Comment by mewmew** [comment]
> Does step 7 fail consistently or intermittently? I can't repro and this point of failure seems very arbitrary. It would almost make more sense to me if it was failing sometimes and succeeding at others. If you can get it to fail consistently, do me a favor and build the step to an executable, and run `gdb <go exe>` and `run` - that should I believe get us an actual stack trace for the failure point in C code

Hmm, that's weird. I thought it was a consistent failure. But now it doesn't fail when I try to re-run it. So I guess it's just flaky. I tried to re-run it 10 or so times on both X11 and Wayland, and was unable to reproduce the crash.

**Comment by CannibalVox** [comment]
Well that's way, way worse but it does make more sense given the stack trace and the problem you had with step 21 (which I assume is the same deal). The surprising thing to me is that it failed here with `CreateLoaderFromProcAddr`, which is the first time go interacts with vkng code, I believe.  It makes me wonder if SDL was contributing?

**Comment by CannibalVox** [comment]
Normally I'd be inclined to be a little suspicious of `cgoparam` in cases like this, but I don't think it's been called yet at that point in the program. In fact, other than calls into SDL2, I think that the only cgo interactions the program has had at that point is C.malloc'ing the funcptr struct, and calling into the method where it crashed. So I'm very suspicious of go-sdl2, or the specific SDL2 binaries that were being linked.

**Comment by mewmew** [comment]
As I've been unable to reproduce this, it seems quite flaky. I think we can close this for now, and if I find a way to reproduce it or if it reappears in other contexts, I can try to dump the GDB back trace. Lets close this for now.
